id = "heta"
name = "Heta"
version = "0.1.0"
schema_version = 1
authors = ["Alexander Stepanov <stepanov@insysbio.com>"]
description = "Heta syntax highlighting for Zed."
repository = "https://github.com/hetalang/zed-heta"

[grammars.heta]
repository = "https://github.com/hetalang/tree-sitter-heta"
commit = "v0.1.0"
