id = "heta-highlight-zed"
name = "Heta Highlight for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Alexander Stepanov <stepanov@insysbio.com>"]
description = "Heta syntax highlighting for Zed."
repository = "https://github.com/hetalang/zed-heta"

[grammars.heta]
repository = "https://github.com/hetalang/tree-sitter-heta"
commit = "bc578e4a01595003697bfa129b902bef8df46885"
