id = "heta"
name = "Heta"
version = "0.1.0"
schema_version = 1
authors = ["Alexander Stepanov <stepanov@insysbio.com>"]
description = "Heta syntax highlighting for Zed."
repository = "https://github.com/hetalang/zed-heta"

[grammars.heta]
repository = "https://github.com/hetalang/tree-sitter-heta"
rev = "df26d5ef6e643d8dacef7f286632e098621b412d"
